name: Publish
on:
  release:
    types:
      - released
  workflow_dispatch:

jobs:
  build:
    uses: srnyx/tools/.github/workflows/publish.yml@main
    with:
      modrinth: f49kyNQQ
      curseforge: 971251
    secrets: inherit
    permissions:
      contents: write
